[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "sentix"
version = "1.0.0"
description = "A lightweight and explainable rule-based sentiment analysis library for Python"

readme = "README.md"

requires-python = ">=3.9"

license = {text = "MIT"}

authors = [
    {name = "Abdul Fathah"}
]


keywords = [
    "sentiment-analysis",
    "nlp",
    "natural-language-processing",
    "sentiment",
    "text-analysis",
    "emotion-analysis",
    "python"
]


classifiers = [
    "Development Status :: 5 - Production/Stable",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",

    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing",
    "Topic :: Text Processing :: Linguistic"
]


dependencies = []


[project.urls]
Homepage = "https://github.com/fathaah910/sentix"
Repository = "https://github.com/fathaah910/sentix"
Issues = "https://github.com/fathaah910/sentix/issues"


# ============================================================
# SETUPTOOLS CONFIGURATION
# Your package is located inside src/sentix
# ============================================================

[tool.setuptools]
package-dir = {"" = "src"}


[tool.setuptools.packages.find]
where = ["src"]
include = ["sentix*"]


# ============================================================
# PYTEST CONFIGURATION
# ============================================================

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]